name: build-binaries
run-name: build binaries for ref ${{ github.ref_name }}

on:
  workflow_dispatch:

jobs:
  build-binaries:
    name: Build Binaries
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Inject Version SHA into Invoke File
        run: |
          echo "using SHA: ${{ github.sha }}"
          sed -i 's|__VERSION_SHA__|${{ github.sha }}|' ./invoke-binary.js

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          cache-dependency-path: "**/go.sum"

      - name: Run Shell Script
        run: |
          chmod +x ./build-binaries.sh
          ./build-binaries.sh ${{ github.sha }}

      - name: Checkout Action Repo
        uses: actions/checkout@v4
        with:
          repository: reywilliams/tf-plan-diff
          token: ${{ secrets.GH_PAT }}
          path: action-repo

      - name: Copy Action Files
        run: |
          cp -v ./invoke-binary.js ./action-repo/
          cp -v ./action.yaml ./action-repo/

          # remove old binaries
          rm -v -f ./action-repo/action-*

          # add new binaries
          cp -v -r ./binaries/* ./action-repo/

      - name: Set up Git
        working-directory: action-repo
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit changes
        working-directory: action-repo
        run: |
          # add new files
          git add .
          git commit -m "update action w/ binaries via workflow 🚀"

      - name: Push changes
        working-directory: action-repo
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: |
          git push origin main
